bundler_args: "--without development"
before_script:
  - "cp config/database.example.yml config/database.yml"
script: "bundle exec rake test:ci"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
notifications:
  irc: "irc.freenode.org#travis"
