bundler_args: "--without development"
before_script:
  - "cp config/database.example.yml config/database.yml"
  - "sh -e /etc/init.d/xvfb start"
script: "DISPLAY=:99.0 bundle exec rake test:ci"
rvm:
  - 1.9.2
  - 1.9.3
notifications:
  irc: "irc.freenode.org#travis"
